exception.user.exists=User with Username/Email_id {0} already exists